name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set up node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: install package json
        run: npm install

      - name: run test
        run: |
          output=$(node dist/Test.js)

          if [ $output != ผิด ]; then
            echo "มันบ่แม่นอ่ะ ไปแก้ใหม่เตอะ ตามนี้ $output"
            exit 1
          fi
