name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print text from index.js
        run: cat dist/index.js
      - name: Checkout code
        uses: actions/checkout@v2
        
